@base_url=127.0.0.1:8000
@token=


###Signup
POST http://{{base_url}}/api/register/
Content-Type: application/json

{
    "username":"Jude193",
    "email":"judefiadzawoo391@gmail.com",
    "password":"jude1233"
}

###Login
POST http://{{base_url}}/api/login/
Content-Type:application/json

{
    "username":"Jude193",
    "password":"jude1233"
}
POST http://{{base_url}}/api/scheduler/23/
Content-Type: application/json
Authorization: Bearer {{token}}