# Generated by Django 5.2.9 on 2025-12-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photovault",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
