# Generated by Django 5.2.9 on 2025-12-31 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="photovault",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Vault.album",
            ),
        ),
    ]
