# Generated by Django 5.2.9 on 2025-12-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0002_alter_album_album_alter_photovault_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
