# Generated by Django 5.2.9 on 2025-12-30 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0002_photovault_uploaded_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photovault",
            old_name="Public",
            new_name="is_public",
        ),
        migrations.AlterField(
            model_name="photovault",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
