# Generated by Django 5.2.9 on 2025-12-31 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0003_alter_album_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album",
            field=models.CharField(default="unknown", max_length=120),
        ),
        migrations.AlterField(
            model_name="photovault",
            name="album",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Vault.album"
            ),
            preserve_default=False,
        ),
    ]
