# Generated by Django 5.2.9 on 2025-12-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0003_rename_public_photovault_is_public_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photovault",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
