# Generated by Django 5.2.9 on 2026-01-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0004_alter_album_album_alter_photovault_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("User", "User"), ("Admin", "Admin")],
                default="User",
                max_length=20,
            ),
        ),
    ]
